app:
  jwt:
    secret: "mySecretKey12345678901234567890123456789012345678901234567890"
    access-token-expiration: 1800000   # 30? (???)
    refresh-token-expiration: 2592000000 # 30? (???)
    issuer: "com.example.app" # issuer ??? .

spring:
  datasource:
    url: jdbc:h2:~/jwt-auth-test;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
logging:
  level:
    com.example: DEBUG
    org.springframework.security: DEBUG
